# Justfile

# Variables
today := `date +'%e-%b-%y_%H-%M-%S'`
varlog := "var/log/"
version := "0.0.1"
venv_dir := "venv"
requirements := "requirements.txt"
results_dir := "results"
backup_results_dir := "var/backup_results"
backup_project_dir := "var/project"
main_file_1 := "auto_roi_criteria_v_dataset.py"
main_file_2 := "auto_roi_criteria_v_window_size.py"

sep := "\n<----------------------------------------------------------------->\n"

# TO DO
# Show operating system
# show-os:
# 	@echo "Operating System: {{os}}"

# Reinstall project from scratch
restart-project:
	@echo " {{sep}} Reinstalling Project...💿 {{sep}} "
	just clean
	@rm -rf {{venv_dir}}
	just install
	@echo " {{sep}} Reinstalled Project ✅ {{sep}} "

# Clean up results directory
clean:
	@echo " {{sep}} Cleaning {{results_dir}} directory...💿 {{sep}} "
	@if [ -d "{{results_dir}}" ]; then rm -rf {{results_dir}}/*; fi
	@echo " {{sep}} Clean Project ✅ {{sep}} "

# Install Python dependencies
install:
	@echo " {{sep}} Installing Python dependencies...💿 {{sep}} "
	@mkdir -p {{results_dir}}
	@python3 -m venv {{venv_dir}}
	@{{venv_dir}}/bin/pip install --upgrade pip
	@{{venv_dir}}/bin/pip install -r {{requirements}}
	@echo " {{sep}} Python dependencies installed  ✅ {{sep}}"

# Add Python module
add module:
	@echo " {{sep}} Adding module...💿 {{sep}} "
	@{{venv_dir}}/bin/pip install {{module}}
	@echo " {{sep}} {{module}} added to the project ✅ {{sep}}"
	just update-requirements

# Update Python dependencies
update-requirements:
	@echo " {{sep}} Updating Python dependencies...💿 {{sep}} "
	@{{venv_dir}}/bin/pip freeze > {{requirements}}
	@echo " {{sep}} Python dependencies updated ✅ {{sep}}"

# Show all the setup scripts in justfile
help:
	@just --list

# Run analysis over datasets
run module:
	@echo " {{sep}} Running  {{module}}...💿 {{sep}} ";
	@(time {{venv_dir}}/bin/python {{module}}) 2>&1 | tee "{{varlog}}{{module}}_{{today}}.log";
	@echo " {{sep}} Finished ...💿 {{sep}} ";

# Run with PyPy

# pypy:
# 	@echo " {{sep}} Running Python script with PyPy...💿 {{sep}} "
# 	@time {{venv_dir}}/bin/python -m pypy3 {{main_file_1}}
# 	@echo "\n"
# 	@time {{venv_dir}}/bin/python -m pypy3 {{main_file_2}}
# 	@echo " {{sep}} Python script run with PyPy ✅ {{sep}} "

# Delete the project and backup results
delete-project:
	@echo " {{sep}} Deleting Project...💿 {{sep}} "
	@rm -rf {{venv_dir}}
	just backup-results
	@echo " {{sep}} Project deleted ✅ {{sep}} "

# Backup results into a zip file
backup-project:
	@echo " {{sep}} Backing up project...💿 {{sep}} "
	@mkdir -p {{backup_project_dir}}
	@zip -r project_backup_$(whoami)_$(date +%Y-%m-%d).zip . -x "{{venv_dir}}/*" "{{results_dir}}/*" ".git/*" "*__pycache__/*" ".vscode/*"
	@mv project_backup_$(whoami)_$(date +%Y-%m-%d).zip {{backup_project_dir}}
	@echo " {{sep}} Backed up complete ✅ {{sep}} "
	just backup-results

# Backup results into a zip file
backup-results:
	@echo " {{sep}} Backing up results...💿 {{sep}} "
	@mkdir -p {{backup_results_dir}}
	@zip -r results_backup_$(whoami)_$(date +%Y-%m-%d).zip {{results_dir}}
	@mv results_backup_$(whoami)_$(date +%Y-%m-%d).zip {{backup_results_dir}}
	@echo " {{sep}} Backed up complete ✅ {{sep}} "

# install pypy3-venv

# run pypy3